CREATE TABLE [dbo].[users]
(
	[ID] NUMERIC NOT NULL PRIMARY KEY IDENTITY, 
    [USERNAME] NVARCHAR(50) NOT NULL, 
    [PASSWORD] NVARCHAR(50) NOT NULL, 
    [GMAIL] NVARCHAR(50) NOT NULL, 
    [GENDER] NVARCHAR(50) NOT NULL
)
